#!/usr/bin/env perl 

my $api = shift @ARGV;
# my $arg = shift @ARGV;

if( ! $api ){
    my $bin = `basename $0`;
    $bin = `trim $bin`;
    print "Usage: $bin <api> [--log] [--token]\n";
    exit(0);
}

## cut /api
#api=${api#\/api}
$api =~ s/^\/api//;

## convert []space with ""
if($api =~ /\?/){
   $api=~s/(\d{4})-(\d{2})-(\d{2}) (\d{2}):(\d{2}):(\d{2})/$1-$2-$3%20$4:$5:$6/g;
}
if($api=~ /\&/){
   $api=~ s/\&/\\\&/g;
}

my $dirname = `dirname $0`;
$dirname =~ s/[\r\t\n]+$//;
my $get_bin = "$dirname/get_token.pl";

## no --token in @ARGV, add into
my $token_flag;
for my $arg (@ARGV){
   if($arg eq '--token'){
      $token_flag=1
   }
}

if(!$token_flag){
   #print "$get_bin $api --token @ARGV\n";
   print `$get_bin $api --token @ARGV`;
}else{
   #print "$get_bin $api @ARGV\n";
   print `$get_bin $api @ARGV`;
}
