#!/usr/bin/env bash
api=$1
data=$2

## cut api
api=${api#\/api}
if [ ! $api ];then
    bin=$(basename $0)
    echo "Usage: $bin <api> <data> [--log] [--token] <token>"
    exit 0
fi

dirname=$(dirname $0)
post_bin=$dirname/post_token.pl

## no --token in @ARGV, add into
unset token_flag
for arg in $@;do
   if [ $arg = '--token' ];then
      token_flag=1
   fi
done
if [ ! $token_flag ];then
   token='--token'
fi

# echo "$post_bin POST $@ $token" > /dev/stderr
$post_bin POST $@ $token
