#!/usr/bin/perl

my $api = shift @ARGV;
my $file = shift @ARGV;

my $print_log;
my $verbose;
foreach(@ARGV){
   if(/--log/){
      $print_log='--log';
   }
   if(/-v/){
      $verbose='-v';
   }
}


if(!$api){
   print "Usage: \n";
   print "  $0 <api> </path/to/file> [--log] [-v]\n";
   exit(0);
}

if($api =~ /\?/){
  $api=~ s/(\d{4})-(\d{2})-(\d{2}) (\d{2}):(\d{2}):(\d{2})/\"$1-$2-$3 $4:$5:$6\"/g;
}
if($api =~ /\&/){
  $api=~ s/\&/\\\&/g;
}

if( $api =~ /^http/){
}else{
  my $in = 'app.endpoint';
  
  my $endpoint;

   my @lines = &get_lines($in);
   foreach (@lines){
      if(/^[\t\n\r\s]+$/){
      }elsif(/^\#/){
      }else{
         $endpoint = $_;
      }
   }

   #my $endpoint = &get_data($in);
   $endpoint =~ s/[\/\r\n]+$//;
   $api = $endpoint.$api;
}

my $in_t = 'app.token';
my $token = &get_data($in_t);

if($print_log){
     print "curl $api -H \"Authorization:Bearer $token\" -F \"file=\@$file\" $verbose\n";
}

print `curl $api -H \"Authorization:Bearer $token\" -F \"file=\@$file\" $verbose`;


sub get_lines {
   my $in = shift;

   my @lines;
   if(-e $in){
      open my $fh, "<", "$in";
        @lines = <$fh>;
      close $fh;
   }
   return @lines;
}

sub get_data {
  my $in = shift;

  my $content;
  local $/; #Enable 'slurp' mode

  open my $fh, "<", "$in";
     $content = <$fh>;
  close $fh;

  $content =~ s/[\r\n\t]+//;

  return $content;
}

