#!/bin/bash
# Parse Markdown test reports generated by run-http-test
# Updated to handle the actual report format

# Parse the test report and output JSON with failure details
parse_report() {
    local report_file="$1"

    if [ -z "$report_file" ]; then
        echo "[$(date '+%Y-%m-%d %H:%M:%S')] ERROR: Report file not provided" >&2
        return 1
    fi

    if [ ! -f "$report_file" ]; then
        echo "[$(date '+%Y-%m-%d %H:%M:%S')] ERROR: Report file does not exist: $report_file" >&2
        return 1
    fi

    if ! command -v jq >/dev/null 2>&1; then
        echo "[$(date '+%Y-%m-%d %H:%M:%S')] ERROR: jq is required but not installed" >&2
        return 1
    fi

    local total=0
    local passed=0
    local failed=0
    local skipped=0

    # Extract summary from report header
    total=$(grep "Total Tests:" "$report_file" | grep -oE '[0-9]+' | head -1 || echo 0)
    passed=$(grep "Passed:" "$report_file" | grep -oE '[0-9]+' | head -1 || echo 0)
    failed=$(grep "Failed:" "$report_file" | grep -oE '[0-9]+' | head -1 || echo 0)
    skipped=$(grep "Skipped:" "$report_file" | grep -oE '[0-9]+' | head -1 || echo 0)

    # Build failures JSON array
    local failures_json="[]"
    local failures_temp=""

    if [ "$failed" -gt 0 ]; then
        # Parse failed test cases
        local current_test=""
        local in_test=0
        local in_response=0
        local response_json=""

        while IFS= read -r line; do
            # Check for failed test marker
            if echo "$line" | grep -q "^### ❌"; then
                in_test=1
                current_test="{"
                in_response=0
                response_json=""

                # Extract title from the same line
                local title
                title=$(echo "$line" | sed 's/^### ❌[[:space:]]*//' | sed 's/[[:space:]]*$//')
                current_test="$current_test\"title\":\"$title\","
                continue
            fi

            # Check for passed test marker (end of failed section)
            if echo "$line" | grep -q "^### ✅" && [ "$in_test" -eq 1 ]; then
                in_test=0
                continue
            fi

            # End of test case section
            if echo "$line" | grep -q "^---$" && [ "$in_test" -eq 1 ]; then
                # Close the failure entry
                if [ -n "$response_json" ]; then
                    # Extract message from response JSON using jq
                    local error_msg
                    error_msg=$(echo "$response_json" | jq -r '.message // . // empty' 2>/dev/null)

                    if [ -n "$error_msg" ] && [ "$error_msg" != "empty" ]; then
                        # Use jq to properly escape the message
                        local escaped_msg
                        escaped_msg=$(echo -n "$error_msg" | jq -Rs .)
                        current_test="${current_test}\"response\":${escaped_msg},"
                    fi
                fi

                current_test="${current_test%,}}"
                if [ -n "$failures_temp" ]; then
                    failures_temp="$failures_temp,$current_test"
                else
                    failures_temp="$current_test"
                fi
                in_test=0
                current_test=""
                continue
            fi

            if [ "$in_test" -eq 1 ]; then
                # Extract method
                if echo "$line" | grep -q "\\*\\*Method:\\*\\*"; then
                    local method
                    method=$(echo "$line" | sed 's/.*\*\*Method:\*\*[[:space:]]*//' | sed 's/[[:space:]]*$//')
                    current_test="$current_test\"method\":\"$method\","
                fi

                # Extract URL
                if echo "$line" | grep -q "\\*\\*URL:\\*\\*"; then
                    local url
                    url=$(echo "$line" | sed 's/.*\*\*URL:\*\*[[:space:]]*//' | sed 's/[[:space:]]*$//')
                    current_test="$current_test\"url\":\"$url\","
                fi

                # Extract status code
                if echo "$line" | grep -q "\\*\\*Status:\\*\\*"; then
                    local http_status
                    http_status=$(echo "$line" | sed 's/.*\*\*Status:\*\*[[:space:]]*//' | sed 's/[[:space:]]*$//')
                    current_test="$current_test\"status\":$http_status,"
                fi

                # Capture response JSON
                if echo "$line" | grep -q '```json'; then
                    in_response=1
                    continue
                fi

                if [ "$in_response" -eq 1 ]; then
                    if echo "$line" | grep -q '^```$'; then
                        in_response=0
                        continue
                    fi
                    # Accumulate response lines
                    response_json="$response_json$line"
                fi
            fi
        done < "$report_file"
    fi

    # Build final JSON output
    local json_output
    if [ -n "$failures_temp" ]; then
        failures_json="[$failures_temp]"
    fi

    json_output=$(jq -n \
        --argjson total "$total" \
        --argjson passed "$passed" \
        --argjson failed "$failed" \
        --argjson skipped "$skipped" \
        --argjson failures "$failures_json" \
        '{
            total: $total,
            passed: $passed,
            failed: $failed,
            skipped: $skipped,
            all_passed: ($failed == 0),
            failures: $failures
        }')

    echo "$json_output"

    # Return 0 if all passed, 1 if there are failures
    [ "$failed" -eq 0 ]
}

# Get count of failed tests
get_failed_count() {
    local report_file="$1"
    local json_result
    json_result=$(parse_report "$report_file")
    echo "$json_result" | jq -r '.failed'
}

# Check if all tests passed
all_tests_passed() {
    local report_file="$1"
    local json_result
    json_result=$(parse_report "$report_file")
    echo "$json_result" | jq -r '.all_passed'
}

# Get the path to the test report
get_report_path() {
    local test_file="$1"
    local output_dir="$2"
    local report_name="${3:-}"

    local test_dir
    local test_basename

    test_dir=$(dirname "$test_file")
    test_basename=$(basename "$test_file" .http)

    if [ -z "$output_dir" ]; then
        output_dir="$test_dir/output"
    fi

    if [ -z "$report_name" ]; then
        report_name="$test_basename"
    fi

    echo "$output_dir/$report_name.md"
}

# Check if report exists
report_exists() {
    local report_path="$1"
    [ -f "$report_path" ]
}

# Get failures as formatted text
get_failures_text() {
    local report_file="$1"
    local json_result
    json_result=$(parse_report "$report_file")

    local failed_count
    failed_count=$(echo "$json_result" | jq -r '.failed')

    if [ "$failed_count" -eq 0 ]; then
        echo "No failures"
        return 0
    fi

    echo "Failed Tests ($failed_count):"
    echo "$json_result" | jq -r '.failures[] | "  - \(.title): \(.method) \(.url) → \(.status)"'
}

# Export functions
export -f parse_report
export -f get_failed_count
export -f all_tests_passed
export -f get_report_path
export -f report_exists
export -f get_failures_text
