#!/usr/bin/env bash

cmd=$1
url=$2

function initDir() {
    echo "init  dir.."
    if [ ! -d "./public/logs" ];then
        mkdir -p public/logs
    fi
    if [ ! -d "./temp" ];then
        mkdir temp
    fi
}


if [ "$cmd"x == "install"x ];then
    #echo "init workspace..."
    #node init.js
    echo "init api-gen..."
    (cd cli-tools/api-gen && npm install)
    echo "init pretty-json..."
    (cd cli-tools/pretty-json && npm install )
    echo "init zero-json..."
    (cd cli-tools/zero-json && npm install)
    echo "init zero-test..."
    npm install -g yarn
    yarn install
    initDir
    exit 0
elif [ "$cmd"x == "update"x ];then
    echo "init workspace..."
    node init.js
    echo "update api-gen..."
    (cd cli-tools/api-gen && npm install)
    echo "update pretty-json..."
    (cd cli-tools/pretty-json && npm install )
    echo "update zero-json..."
    (cd cli-tools/zero-json && npm install)
    echo "update zero-test..."
    npm install -g
    exit 0
elif [ "$cmd"x == "repair"x ];then
    echo "init workspace..."
    node init.js
    if [ -f "package-lock.json" ];then
        rm package-lock.json
    fi
    if [ -f "./cli-tools/api-gen/package-lock.json" ];then
        rm ./cli-tools/api-gen/package-lock.json
    fi
    if [ -f "./cli-tools/pretty-json/package-lock.json" ];then
        rm ./cli-tools/pretty-json/package-lock.json
    fi
    if [ -f "./cli-tools/zero-json/package-lock.json" ];then
        rm ./cli-tools/zero-json/package-lock.json
    fi
    echo "repair api-gen..."
    (cd cli-tools/api-gen && npm uninstall api-gen -g && npm install)
    echo "repair pretty-json..."
    (cd cli-tools/pretty-json && npm uninstall pretty-json -g && npm install )
    echo "repair zero-json..."
    (cd cli-tools/zero-json && npm uninstall zero-json -g && npm install)
    echo "repair zero-test..."
    npm uninstall zero-test  -g && npm install  -g
    initDir
    echo "Done!"
    exit 0
elif [ "$cmd"x == "map"x -a "$url"x != ""x ];then
    echo "map zero-test to $url ..."
    cp -r test-env/ $url/
    if [ ! -d "$url/public/logs" ];then
        mkdir -p "$url/public/logs"
    fi
    echo "done!"
    exit 0
fi


echo "Usage: ./init [install | update | repair | map <path>";
