#!/usr/bin/env bash

cmd=$1
opt=$2
url=$3

if [ "$cmd"x == "install"x ];then
    echo "init..."
    cnpm install -g
    echo "init api-gen..."
    (cd cli-tools/api-gen && cnpm install)
    echo "init pretty-json..."
    (cd cli-tools/pretty-json && cnpm install )
    echo "init zero-json..."
    if [ ! -d "./swagger" ];then
        mkdir swagger
    fi
    if [ ! -d "./cli-tools/zero-json/swagger" ];then
        mkdir ./cli-tools/zero-json/swagger
    fi
    (cd cli-tools/zero-json && cnpm install \
    && curl $swagger --out swagger/index.json \
    node index.js swagger format && mv swagger/format.json ../../swagger/swagger.json)
    exit 0
elif [ "$cmd"x == "get"x -a "$opt"x == "swagger"x ];then
    if [ ! -d "./swagger" ];then
        mkdir swagger
    fi
    (cd cli-tools/zero-json && \
    curl $url --out swagger/index.json && \
    node index.js swagger format && mv swagger/format.json ../../swagger/swagger.json)
    exit 0
fi

echo "Usage: ./init [install | get swagger <url>]";
