version: '3.4'
services:
  zero-test:
    image: zero-test
    container_name: zero-test
    build:
      context: ../.
      dockerfile: ./Docker/Dockerfile
    environment:
      NODE_ENV: production
    # volumes:
      # ./config/server.config:/usr/src/app/config/server.config
    command: 
      - "--help"
      