version: '3.4'
services:
  zerotest:
    image: zero-test
    container_name: zero-test
    build:
      context: ../.
      dockerfile: ./Docker/Dockerfile
    environment:
      NODE_ENV: production
      