DROP TABLE IF EXISTS `company_info`;
CREATE TABLE `company_info` (
  `id` varchar(40) NOT NULL COMMENT 'id，与登录用户的id同',
  `user_id` varchar(40) DEFAULT NULL COMMENT '机构用户id',
  `name` varchar(100) DEFAULT NULL COMMENT '名称',
  `type` varchar(50) DEFAULT NULL COMMENT '类型',
  `licence_no` varchar(50) DEFAULT NULL COMMENT '营业执照号',
  `address` varchar(100) DEFAULT NULL COMMENT '住所',
  `legal_representative` varchar(50) DEFAULT NULL COMMENT '法人',
  `startup_date` date DEFAULT NULL COMMENT '成立日期',
  `capital` double DEFAULT '0' COMMENT '注册资本',
  `start_date` date DEFAULT NULL COMMENT '营业期限开始',
  `expire_date` date DEFAULT NULL COMMENT '营业期限结束',
  `business_scope` varchar(255) DEFAULT NULL COMMENT '经营范围',
  `signed_date` date DEFAULT NULL COMMENT '签发日期',
  `cert_status` tinyint(1) DEFAULT '0' COMMENT '认证状态：0未认证，1审核中，2通过，3未通过',
  `location` geometry DEFAULT NULL COMMENT '位置信息',
  `longitude` decimal(10,7) DEFAULT NULL COMMENT '经度',
  `latitude` decimal(10,7) DEFAULT NULL COMMENT '纬度',
  `applicant` varchar(50) DEFAULT NULL COMMENT '申请人',
  `applicant_phone` varchar(50) DEFAULT NULL COMMENT '申请人手机',
  `place_name` varchar(100) DEFAULT NULL COMMENT '场所名称',
  `place_address` varchar(100) DEFAULT NULL COMMENT '场所地址',
  `length` double(10,2) DEFAULT NULL COMMENT '长度',
  `width` double(10,2) DEFAULT NULL COMMENT '宽度',
  `area` double(10,2) DEFAULT NULL COMMENT '面积',
  `representative_name` varchar(50) DEFAULT NULL COMMENT '法人姓名',
  `representative_id_no` varchar(50) DEFAULT NULL COMMENT '法人身份证号',
  `person_name` varchar(50) DEFAULT NULL COMMENT '负责人姓名',
  `person_id_no` varchar(50) DEFAULT NULL COMMENT '负责人身份证号',
  `person_phone` varchar(50) DEFAULT NULL COMMENT '负责人手机',
  `person_address` varchar(255) DEFAULT NULL COMMENT '负责人住址',
  `op_unit_name` varchar(100) DEFAULT NULL COMMENT '经营单位名称',
  `op_unit_address` varchar(100) DEFAULT NULL COMMENT '经营单位地址',
  `op_unit_phone` varchar(50) DEFAULT NULL COMMENT '经营单位固话',
  `operation_item` varchar(200) DEFAULT NULL COMMENT '经营项目',
  `operation_place` varchar(100) DEFAULT NULL COMMENT '经营场所',
  `created_time` datetime DEFAULT NULL COMMENT '创建日期',
  `updated_time` datetime DEFAULT NULL COMMENT '更新日期',
  `deleted` tinyint(1) DEFAULT '0' COMMENT '是否删除',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

