## node index.js test public/testcase/org.test.http output/org.http.pdf
@endpoint=http://192.168.3.239:8000
@token = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJvcmdJZCI6IjEwMDAwMDAwMDAwMDAwMDAwMSIsInVzZXJJZCI6Ijg3NjcwODA4MjQzNzE5Nzg1MiIsInVzZXJUeXBlIjoxMDEsImJVc2VyVHlwZSI6IlNZU1RFTSIsInRlbmFudE9yZ0lkIjoxMDAwMDAwMDAwMDAwMDAwMDEsImFjY291bnQiOiJhZG1pbiIsImV4dHJhVXNlclR5cGUiOjAsImlhdCI6MTYzNTIxMTc0MSwianRpIjoiODc2NzA4MDgyNDM3MTk3ODUyIiwic3ViIjoiYWRtaW4iLCJleHAiOjE2MzU0NzA5NDF9.TNI-1MakFHoF9xtB9FsiSbF97YY4_Tt6PoN2ZKj5GiNyY1BDsl-Jo1-PYKJd4qypqNOPFIxKxzxncXkhEY43jA

GET {{endpoint}}/api/sys/org
Authorization: Bearer {{token}}
